name: deepfake_app
description: An app that classifies real faces and fake faces.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

module:
  androidX: true

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  video_player: ^2.3.0
  youtube_player_flutter: ^8.0.0
  image_picker: ^0.8.4+11
  chewie: ^1.3.1
  url_launcher: ^6.0.20
  file_picker: ^4.5.1
  dio: ^4.0.4
  flutter_downloader: ^1.7.3
  external_path: ^1.0.1
  permission_handler: ^9.2.0
  provider: ^6.0.2
  http: ^0.13.4
  image_picker_platform_interface: ^2.4.4
  flutter_localizations:
    sdk: flutter

flutter:
  assets:
    - assets/
    - lang/en.json
    - lang/hi.json
    - lang/gu.json
    - lang/bn.json
    - lang/mr.json
    - lang/ml.json
    - lang/te.json
    - lang/pa.json

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
